// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PsMarketApp.Data;

#nullable disable

namespace PsMarketApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214173903_SliderSistemi")]
    partial class SliderSistemi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("PsMarketApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SliderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vitrin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SliderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PsMarketApp.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Slider");
                });

            modelBuilder.Entity("PsMarketApp.Models.Product", b =>
                {
                    b.HasOne("PsMarketApp.Models.Slider", "Slider")
                        .WithMany("Products")
                        .HasForeignKey("SliderId");

                    b.Navigation("Slider");
                });

            modelBuilder.Entity("PsMarketApp.Models.Slider", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
